cmake -S . -B out/release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_COMPILER:FILEPATH=clang -DCMAKE_CXX_COMPILER:FILEPATH=clang++ -DCMAKE_LINKER=lld -DCMAKE_BUILD_TYPE=Release
cmake --build out/release
