[package]
name = "cake"
version = "0.0.1"
authors = "Civitasv"
description = "Cake, CMake without a mess"
license = "MIT"
default-run = "cake"

[profile]
c_compiler = "clang"
cxx_compiler = "clang++"
linker = "lld"
debugger = "lldb" # "gdb", "lldb", "code"
build-type = "Release" #  "Debug", "Release", "RelWithDebInfo", "MinSizeRel" 
build-directory = "out/release"
compile-commands = true
vcpkg = false
