[package]
name = "basic_template"
version = "0.0.1"
authors = "Civitasv"
description = "Basic template for Cake(without vcpkg support)"
license = "MIT"
default-run = "basic"

[[lib]]

[[bin]]
name = "basic"
build-type = "release"

[profile]
vcpkg = false
c_compiler = "clang"
cxx_compiler = "clang++"
linker = "lld"
debugger = "lldb" # "lldb", "gdb", "code"
build-type = "Debug" # "Debug", "Release", "RelWithDebInfo", "MinSizeRel".
build-directory = "out/debug"
compile_commands = true
