[package]
name = "vcpkg_template"
version = "0.0.1"
authors = "Civitasv"
description = "Vcpkg template for Cake(with vcpkg support)"
license = "MIT"
default-run = "vcpkg"

[[lib]]

[[bin]]
name = "vcpkg"
build-type = "release"

[profile]
vcpkg = true
c_compiler = "clang"
cxx_compiler = "clang++"
linker = "lld"
debugger = "lldb" # "lldb", "gdb", "code"
build-type = "Debug" # "Debug", "Release", "RelWithDebInfo", "MinSizeRel".
build-directory = "out/debug"
compile_commands = true
